// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam_app/test/src/domain/use_case/mocked/moked_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam_app/core/api/common/api_result.dart' as _i4;
import 'package:online_exam_app/src/data/model/request/change_password_request.dart'
    as _i10;
import 'package:online_exam_app/src/data/model/request/login_request.dart'
    as _i6;
import 'package:online_exam_app/src/data/model/request/register_request.dart'
    as _i8;
import 'package:online_exam_app/src/data/model/request/update_profile_request.dart'
    as _i9;
import 'package:online_exam_app/src/domain/entities/app_user_entity.dart'
    as _i5;
import 'package:online_exam_app/src/domain/entities/subject_entity.dart'
    as _i12;
import 'package:online_exam_app/src/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:online_exam_app/src/domain/repositories/subject_repository.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.AppUserEntity>> login(
          {required _i6.LoginRequest? loginRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#loginRequest: loginRequest},
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.AppUserEntity>>(
          this,
          Invocation.method(
            #login,
            [],
            {#loginRequest: loginRequest},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.AppUserEntity>> register(
          {required _i8.RegisterRequest? registerRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {#registerRequest: registerRequest},
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.AppUserEntity>>(
          this,
          Invocation.method(
            #register,
            [],
            {#registerRequest: registerRequest},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.AppUserEntity>> getProfileData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.AppUserEntity>>(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.AppUserEntity>> updateProfile(
          {required _i9.UpdateProfileRequest? updateProfileRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {#updateProfileRequest: updateProfileRequest},
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.AppUserEntity>>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {#updateProfileRequest: updateProfileRequest},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.AppUserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<bool>> changePassword(
          {required _i10.ChangePasswordRequest? changePasswordRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {#changePasswordRequest: changePasswordRequest},
        ),
        returnValue: _i3.Future<_i4.ApiResult<bool>>.value(
            _i7.dummyValue<_i4.ApiResult<bool>>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {#changePasswordRequest: changePasswordRequest},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<bool>>);
}

/// A class which mocks [SubjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubjectRepository extends _i1.Mock implements _i11.SubjectRepository {
  MockSubjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i12.SubjectEntity>>> getAllSubject() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSubject,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i12.SubjectEntity>>>.value(
            _i7.dummyValue<_i4.ApiResult<List<_i12.SubjectEntity>>>(
          this,
          Invocation.method(
            #getAllSubject,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i12.SubjectEntity>>>);
}
