// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam_app/test/src/data/repositories/exam_repository_impl/exam_repository_imol_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/src/data/data_source/online_data_source/exam_online_data_source/exam_online_data_source.dart'
    as _i3;
import 'package:online_exam_app/src/data/mappers/exam_mapper.dart' as _i5;
import 'package:online_exam_app/src/data/model/response/exam_response_model/exam_response_model.dart'
    as _i2;
import 'package:online_exam_app/src/domain/entities/exam_entity.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExamResponseModel_0 extends _i1.SmartFake
    implements _i2.ExamResponseModel {
  _FakeExamResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExamOnlineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamOnlineDataSource extends _i1.Mock
    implements _i3.ExamOnlineDataSource {
  MockExamOnlineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExamResponseModel> getExamOnSubjectId(
          {required String? subjectId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamOnSubjectId,
          [],
          {#subjectId: subjectId},
        ),
        returnValue:
            _i4.Future<_i2.ExamResponseModel>.value(_FakeExamResponseModel_0(
          this,
          Invocation.method(
            #getExamOnSubjectId,
            [],
            {#subjectId: subjectId},
          ),
        )),
      ) as _i4.Future<_i2.ExamResponseModel>);
}

/// A class which mocks [ExamMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamMapper extends _i1.Mock implements _i5.ExamMapper {
  MockExamMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.ExamEntity> toExamEntity(_i2.ExamResponseModel? examResponseModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #toExamEntity,
          [examResponseModel],
        ),
        returnValue: <_i6.ExamEntity>[],
      ) as List<_i6.ExamEntity>);
}
