name : Build Apk WorkFlow

on:
  push:

jobs:
  build-apk:
    name:
    runs-on:  ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
    - name: Install Dependence
      run: flutter pub get
    - name: Build Apk
      run: flutter build apk --release
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk