name : Unit Test WorkFlow

on:
  push:
    branches:
jobs:
  test:
    name: run flutter test all branches
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: install package
        run: flutter pub get
      - name: run flutter test
        run : flutter test
      - name : run flutter test with coverage
        run : flutter test coverage
