 name : Test Flutter WorkFlow

 on:
   push:

   pull_request:


 jobs:
   test:
     name: run flutter test ubuntu
     run-on: ubuntu-latest

   steps:
    - name: checkOut Code
      uses: actions/cache@v3

    - name: install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter_version: 3.22.2

    - name: Install package
      run : flutter pub get
    - name : run flutter test
      run : flutter test
    - name: run flutter test wiht coverage
      run : flutter test --coverage
    - name: upload coverge result
      uses: actions/upload-artifact@v3
      with:
        name: flutter-coverage
        path: coverage/lcov-report/