# name : Test Flutter WorkFlow
#
# on:
#   push:
#     branches:
#
# jobs:
#   test:
#     name: run flutter test ubuntu
#     runs-on: ubuntu-latest
#
#   steps:
#    - name: checkOut Code
#      uses: actions/checkout@v3
#
#    - name: install Flutter
#      uses: subosito/flutter-action@v2
#      with:
#        flutter-version: '3.22.2'
#    - name: Install package
#      run : flutter pub get
#    - name : run flutter test
#      run : flutter test
#    - name: run flutter test wiht coverage
#      run : flutter test --coverage
#    - name: upload coverge result
#      uses: actions/upload-artifact@v3
#      with:
#        name: flutter-coverage
#        path: coverage/

name: Test Flutter WorkFlow

on:
  push:
    branches:

jobs:
  test:
    name: Run Flutter Test on Ubuntu
    runs-on: ubuntu-latest  # يجب أن يكون runs-on وليس run-on

    steps:
      # خطوة 1: Checkout الكود من المستودع
      - name: Checkout Code
        uses: actions/checkout@v3  # استخدم actions/checkout بدلاً من actions/cache

      # خطوة 2: تثبيت Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'  # يجب استخدام flutter-version وليس flutter_version

      # خطوة 3: تثبيت التبعيات
      - name: Install Dependencies
        run: flutter pub get

      # خطوة 4: تشغيل اختبارات الوحدة
      - name: Run Flutter Tests
        run: flutter test

      # خطوة 5: تشغيل اختبارات مع التغطية
      - name: Run Flutter Tests with Coverage
        run: flutter test --coverage

      # خطوة 6: رفع نتائج التغطية كـ Artifact
      - name: Upload Coverage Result
        uses: actions/upload-artifact@v3
        with:
          name: flutter-coverage
          path: coverage/lcov-report/  # تأكد من المسار الصحيح
